/* Auto-generated by export.py — do not edit by hand */
window.EXPENSE_DATA = [
  {
    "id": 11,
    "date": "2026-08-06",
    "category": "food",
    "amount": 400.0,
    "note": "food",
    "type": "expense"
  },
  {
    "id": 12,
    "date": "2026-08-06",
    "category": "travel",
    "amount": 300.0,
    "note": "travel",
    "type": "expense"
  }
];
window.EXPENSE_CONFIG = {
  "currency": "₹",
  "monthlyBudget": 50000,
  "budgets": {
    "travel": 5000,
    "food": 8000,
    "groceries": 6000,
    "clothes": 3000,
    "rent": 15000,
    "bills": 4000,
    "luxuries": 3000,
    "investments": 10000,
    "health": 2000,
    "education": 2000,
    "other": 2000
  }
};
