/* Auto-generated by export.py — do not edit by hand */
window.EXPENSE_DATA = [
  {
    "id": 8,
    "date": "2026-08-06",
    "category": "loans",
    "amount": 2000.0,
    "note": "Rushil",
    "type": "lend"
  }
];
window.EXPENSE_CONFIG = {
  "currency": "₹",
  "monthlyBudget": 50000,
  "budgets": {
    "travel": 5000,
    "food": 8000,
    "groceries": 6000,
    "clothes": 3000,
    "rent": 15000,
    "bills": 4000,
    "luxuries": 3000,
    "investments": 10000,
    "health": 2000,
    "education": 2000,
    "other": 2000
  }
};
