/* Auto-generated by export.py — do not edit by hand */
window.EXPENSE_DATA = [
  {
    "id": 13,
    "date": "2026-08-07",
    "category": "rent",
    "amount": 29000.0,
    "note": "Rent",
    "type": "expense"
  },
  {
    "id": 14,
    "date": "2026-08-07",
    "category": "other",
    "amount": 880.0,
    "note": "Other",
    "type": "expense"
  },
  {
    "id": 15,
    "date": "2026-08-07",
    "category": "loans",
    "amount": 1850.0,
    "note": "Sukhada",
    "type": "lend"
  },
  {
    "id": 17,
    "date": "2026-08-07",
    "category": "luxuries",
    "amount": 300.0,
    "note": "spotify subscription",
    "type": "expense"
  },
  {
    "id": 18,
    "date": "2026-08-07",
    "category": "other",
    "amount": 100.0,
    "note": "Google one subscription",
    "type": "expense"
  },
  {
    "id": 20,
    "date": "2026-08-08",
    "category": "food",
    "amount": 60.0,
    "note": "food",
    "type": "expense"
  },
  {
    "id": 21,
    "date": "2026-08-08",
    "category": "other",
    "amount": 100.0,
    "note": "haircut",
    "type": "expense"
  },
  {
    "id": 22,
    "date": "2026-08-08",
    "category": "groceries",
    "amount": 60.0,
    "note": "milk",
    "type": "expense"
  },
  {
    "id": 24,
    "date": "2026-08-08",
    "category": "groceries",
    "amount": 425.0,
    "note": "Mop,utensil washer groceries",
    "type": "expense"
  },
  {
    "id": 25,
    "date": "2026-08-08",
    "category": "other",
    "amount": 1428.0,
    "note": "Bathroom materials",
    "type": "expense"
  },
  {
    "id": 26,
    "date": "2026-08-08",
    "category": "food",
    "amount": 270.0,
    "note": "food",
    "type": "expense"
  }
];
window.EXPENSE_CONFIG = {
  "currency": "₹",
  "monthlyBudget": 50000,
  "budgets": {
    "travel": 5000,
    "food": 8000,
    "groceries": 6000,
    "clothes": 3000,
    "rent": 15000,
    "bills": 4000,
    "luxuries": 3000,
    "investments": 10000,
    "health": 2000,
    "education": 2000,
    "other": 2000
  }
};
