"""
Export SQLite transactions + safe config slice into data.js for the dashboard.

The dashboard loads this via <script src="data.js"> so it works from file://
with no server and no fetch(). The Telegram bot token is NEVER written here.
"""

from __future__ import annotations

import json
import logging
import subprocess
from pathlib import Path
from typing import Any

import db

log = logging.getLogger("export")

ROOT = Path(__file__).resolve().parent
CONFIG_PATH = ROOT / "config.json"
DATA_JS_PATH = ROOT / "data.js"


def _load_config() -> dict[str, Any]:
    with open(CONFIG_PATH, encoding="utf-8") as f:
        return json.load(f)


def _public_config(cfg: dict[str, Any]) -> dict[str, Any]:
    """Strip secrets before anything reaches the browser."""
    return {
        "currency": cfg.get("currency", "₹"),
        "monthlyBudget": cfg.get("monthlyBudget", 0),
        "budgets": cfg.get("budgets", {}),
    }


def _row_for_js(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": row["id"],
        "date": row["date"],
        "category": row["category"],
        "amount": row["amount"],
        "note": row["note"],
        "type": row["type"],
    }


def export(path: Path | None = None) -> Path:
    """Rebuild data.js from the current database + config. Returns the path written."""
    out = path or DATA_JS_PATH
    cfg = _load_config()
    rows = [_row_for_js(r) for r in db.all_rows()]
    public = _public_config(cfg)

    # Compact but readable JSON embedded as JS assignments
    data_json = json.dumps(rows, ensure_ascii=False, indent=2)
    config_json = json.dumps(public, ensure_ascii=False, indent=2)

    contents = (
        "/* Auto-generated by export.py — do not edit by hand */\n"
        f"window.EXPENSE_DATA = {data_json};\n"
        f"window.EXPENSE_CONFIG = {config_json};\n"
    )
    out.write_text(contents, encoding="utf-8")
    return out


def _git_push_data(data_file: Path) -> None:
    """Commit and push data.js so Vercel redeploys with fresh numbers."""
    root = ROOT
    if not (root / ".git").is_dir():
        log.warning("github_sync skipped: no git repo in %s", root)
        return
    name = data_file.name
    subprocess.run(["git", "add", name], cwd=root, check=True, capture_output=True)
    staged = subprocess.run(
        ["git", "diff", "--cached", "--quiet", name],
        cwd=root,
        capture_output=True,
    )
    if staged.returncode == 0:
        return
    subprocess.run(
        ["git", "commit", "-m", "chore: update dashboard data"],
        cwd=root,
        check=True,
        capture_output=True,
    )
    subprocess.run(["git", "push"], cwd=root, check=True, capture_output=True, timeout=120)
    log.info("Pushed %s to GitHub for Vercel", name)


def export_and_publish(path: Path | None = None) -> Path:
    """Write data.js and optionally push to GitHub (see github_sync in config)."""
    out = export(path)
    cfg = _load_config()
    if cfg.get("github_sync"):
        try:
            _git_push_data(out)
        except subprocess.CalledProcessError as exc:
            log.warning("github_sync failed: %s", exc.stderr.decode() if exc.stderr else exc)
        except OSError as exc:
            log.warning("github_sync failed: %s", exc)
    return out


if __name__ == "__main__":
    target = export_and_publish()
    print(f"Wrote {target} ({target.stat().st_size} bytes)")
